### PR TITLE
Added peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by PeterBell** [comment]
Would be better with some test coverage

**Comment by PeterBell** [comment]
:+1: LGTM let's :ship: it

**Comment by madmike210** [comment]
:8ball:

**Comment by atownag** [comment]
Needs more Star Wars references

**Comment by madmike210** [comment]
Taco Truck Player!

**Comment by PeterBell** [comment]
colbert

**Comment by srgray** [comment]
Nead to spellchck these chanjes

**Comment by githubteacher** [comment]
LGTM :+1:

**Comment by DerekOates** [comment]
Выглядит хорошо для меня

**Pull request merged**
